spring.application.name=pre-assignment

# ??? 8080 ?? (?????? ?? ??)
# server.port=8080

# ??? ?? ??. ???? ??
spring.output.ansi.enabled=always

# ?? ?? ?? (API?? ?? ?? ? ?)
#server.servlet.session.tracking-modes=cookie

# ?? ??
logging.level.root=info
logging.level.org.example=debug

# DB ??
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/wanted31
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

# MyBatis ??
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mybatis/mappers/**/*.xml